[package]
name = "rust-hangman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = "0.11.11"
futures = "0.3.24"
tokio = "1.21.1"
serde_json = "1.0.85"